version: "3.7"

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV-development}
    command: node_modules/.bin/nodemon src/index.js
    ports:
      - "3000:3000"
    tty: true
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV-development}
    volumes:
      - .:/opt/app
      - notused:/opt/app/node_modules

volumes:
  notused:
